# Generated by Django 2.1.2 on 2018-10-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
